---
version: "3.5"
services:
  cloudinary:
    ports:
      - '5555:5000'
    image: anthonyrussano/cloudinary:latest
    secrets:
      - cloudinary_api_key
      - cloudinary_api_secret
      - cloudinary_cloud_name

secrets:
  cloudinary_api_key:
    external: true
  cloudinary_api_secret:
    external: true
  cloudinary_cloud_name:
    external: true
